# Generated by Django 6.0 on 2026-01-08 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'navs_menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('url_name', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('target', models.CharField(blank=True, choices=[('_self', 'Open in the Same Tab'), ('_blank', 'Open in a New Tab')], max_length=25)),
                ('classes', models.CharField(blank=True, max_length=255)),
                ('permission', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_links', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navs.link')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='navs.menu')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'db_table': 'navs_links',
                'ordering': ['order'],
            },
        ),
    ]
